name: Update

on: [push]
jobs:
  setup_env:
    name: Update
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions: write-all
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_KEY }}

      - uses: actions/setup-python@v4
      - run: |
          pip install requests
          pip install python-dateutil
          python ./auto_fork.py

      - name: Push
        run: |
          ls
          git add --all
          git commit -am "update"
          git push origin master --force
